### PR TITLE
Adding the Frame 2018

### PR DESCRIPTION
**Pull request by ferdi2005**
UE43LS003 is seen as unparseable from the app and so it can't be added. It's a 2018 The Frame TV.
With this PR I add it.
@mmende

### CODE REVIEW

**Comment by mmende** [comment]
Thanks for the contribution. I will merge it soon.

**Comment by ferdi2005** [comment]
@mmende Do you plan to merge it in the foreseeable future?

**Comment by mmende** [comment]
Merged and published... Sorry for taking so long to merge the PR

**Comment by ferdi2005** [comment]
Don't worry, thank you! @mmende

**Pull request merged**
